### ISSUE TITLE
Extra whitespace rendering between the top of the window and top of the GroupMe client

### ISSUE THREAD

**Issue by morgannewman** [davidcorbin/GroupMe-Desktop#1]
<img width="1283" alt="screen shot 2018-02-21 at 8 39 03 am" src="https://user-images.githubusercontent.com/30091235/36492956-443a66f0-16e3-11e8-8b21-a8a670cf0b7f.png">

Re-creatable on MacOS High Sierra 10.13.3 at 2560×1600 resolution.

**Comment by davidcorbin** [comment]
Hey @morgannewman, try restarting the application and see if that fixes it

**Comment by morgannewman** [comment]
Really jumped the gun reporting this bug... a lesson learned! After restarting my computer, the bug disappeared. Thanks for the prompt response!
